export enum ERROR_MESSAGE_ENUM {
  ERRORMESAGE_PURCHARSE_ORDER_NOT_FOUND = 'ERRORMESAGE_PURCHARSE_ORDER_NOT_FOUND',
  ERRORMESAGE_CODE_MISSMATCH = 'ERRORMESAGE_CODE_MISSMATCH',
  ERRORMESAGE_QUANTITIES_MISSMATCH = 'ERRORMESAGE_QUANTITIES_MISSMATCH',
}
